Move to new structure

diff --git a/.github/workflows/publish-package.yml b/.github/workflows/publish-package.yml
--- a/.github/workflows/publish-package.yml
+++ b/.github/workflows/publish-package.yml
@@ -4,7 +4,6 @@ on:
     branches:
       - main
 
-    # Publish `v1.2.3` tags as releases.
     tags:
       - v*
 
@@ -15,31 +14,67 @@ jobs:
   publish-package:
     runs-on: ubuntu-latest
 
-#{Services}
     steps:
       - uses: actions/checkout@v4
       
       - name: Setting up build version
         run: |
           version=$(($GITHUB_RUN_NUMBER))
-          echo "BUILD_VERSION=2.2.$version" >> ${GITHUB_ENV}
+          echo "BUILD_VERSION=2.1.$version" >> ${GITHUB_ENV}
 
       - name: Setup .NET Core 8.0
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.0.x
 
-      - name: Install dependencies
-        run: dotnet restore
+      - name: Install dependencies with retry
+        run: |
+          retries=5
+          base_wait_time=15
+          exponent=2
+
+          for i in $(seq 1 $retries); do
+            if dotnet restore; then
+              break
+            fi
+
+            if [ $i -lt $retries ]; then
+              wait_time=$(awk "BEGIN {print int($base_wait_time * ($exponent ^ ($i - 1)))}")
+              echo "dotnet restore failed, retrying in $wait_time seconds..."
+              sleep $wait_time
+            else
+              echo "dotnet restore failed after $retries retries."
+              exit 1
+            fi
+          done
 
       - name: Build
         run: dotnet build --configuration Release --no-restore
 
       - name: Test
-        run: dotnet test test/Soenneker.Validators.Email.Disposable.Tests.csproj --no-restore --verbosity normal
+        run: dotnet test test/Soenneker.Validators.Email.Disposable.Tests/Soenneker.Validators.Email.Disposable.Tests.csproj --no-restore --verbosity normal
 
       - name: Pack
         run: dotnet pack --no-build --configuration Release --output .
 
-      - name: Publish to nuGet
-        run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate
+      - name: Publish to NuGet with retry
+        run: |
+          nupkg_files=$(find . -name "*.nupkg")
+          retries=5
+          base_wait_time=20 
+          exponent=3.5
+          
+          for i in $(seq 1 $retries); do
+            if dotnet nuget push $nupkg_files --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate; then
+              break
+            fi
+            
+            if [ $i -lt $retries ]; then
+              wait_time=$(awk "BEGIN {print int($base_wait_time * ($exponent ^ ($i - 1)))}")
+              echo "NuGet publish failed, retrying in $wait_time seconds..."
+              sleep $wait_time
+            else
+              echo "NuGet publish failed after $retries retries."
+              exit 1
+            fi
+          done
